package com.kony.sbg.util;

public enum BOPcategoryMetaDataEnum {
    Code_100("100","Adjustments / Reversals / Refunds applicable to merchandise"),
    Code_101_01("101/01", "Export advance payment"),
    Code_101_02("101/02", "Export advance payment - capital goods"),
    Code_101_03("101/03", "Export advance payment - gold"),
    Code_101_04("101/04", "Export advance payment - platinum"),
    Code_101_05("101/05", "Export advance payment - crude oil"),
    Code_101_06("101/06", "Export advance payment - refined petroleum products"),
    Code_101_07("101/07", "Export advance payment - diamonds"),
    Code_101_08("101/08", "Export advance payment - steel"),
    Code_101_09("101/09", "Export advance payment - coal"),
    Code_101_10("101/10", "Export advance payment - iron ore"),
    Code_101_11("101/11", "Export advance payment - goods exported via the South African Post Office"),
    Code_103_01("103/01", "Export payments"),
    Code_103_02("103/02", "Export payment - capital goods"),
    Code_103_03("103/03", "Export payment - gold"),
    Code_103_04("103/01", "Export payment - platinum"),
    Code_103_05("103/01", "Export payment - crude oil"),
    Code_103_06("103/01", "Export payment - refined petroleum products"),
    Code_103_07("103/07", "Export payment - diamonds"),
    Code_103_08("103/01", "Export payment - steel"),
    Code_103_09("103/01", "Export payment - coal"),
    Code_103_10("103/10", "Export payment - iron ore"),
    Code_103_11("103/11", "Export payment - goods exported via the South African Post Office"),
    Code_105("105", "Consumables acquired in port"),
    Code_106("106", "Trade finance repayments in respect of exports"),
    Code_107("107", "Export proceeds where the Customs value of the shipment is less than R500"),
    Code_108("108", "Export payments where goods were declared as part of passenger baggage and no UCR is available"),
    Code_109_01("109/01", "Proceeds for goods purchased by non residents where no physical export will take place, excluding the below"),
    Code_109_02("109/02", "Proceeds for gold purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_03("109/03", "Proceeds for platinum purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_04("109/04", "Proceeds for crude oil purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_05("109/05", "Proceeds for refined petroleum products purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_06("109/06", "Proceeds for diamonds purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_07("109/07", "Proceeds for steel purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_08("109/08", "Proceeds for coal purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_109_09("109/09", "Proceeds for iron ore purchased by non residents where no physical export will take place, excluding merchanting transactions"),
    Code_110("110", "Merchanting transaction"),
    Code_200("200", "Adjustments / Reversals / Refunds applicable to intellectual property and service related items"),
    Code_201("201", "Rights assigned for licences to reproduce and/or distribute"),
    Code_202("202", "Rights assigned for using patents and inventions (licensing)"),
    Code_203("203", "Rights assigned for using patterns and designs (including industrial processes)"),
    Code_204("204", "Rights assigned for using copyrights"),
    Code_205("201", "Rights assigned for using franchises and trademarks"),
    Code_210("210", "Disposal of patents and inventions"),
    Code_211("211", "Disposal of patterns and designs (including industrial processes)"),
    Code_212("212", "Disposal of copyrights"),
    Code_213("213", "Disposal of franchises and trademarks"),
    Code_220("220", "Proceeds received for research and development services"),
    Code_221("221", "Funding received for research and development"),
    Code_225("225", "Sales of original manuscripts, sound recordings and films"),
    Code_226("226", "Receipt of funds relating to the production of motion pictures, radio and television programs and musical recordings"),
    Code_230("230", "The outright selling of ownership rights of software"),
    Code_231("231", "Computer-related services including maintenance, repair and consultancy"),
    Code_232("232", "Commercial sales of customised software and related licenses for use by customers"),
    Code_233("233", "Commercial sales of non-customised software on physical media with periodic licence to use"),
    Code_234("234", "Commercial sales of non-customised software provided on physical media with right to perpetual (ongoing) use"),
    Code_235("235", "Commercial sales of non-customised software provided for downloading or electronically made available with periodic license"),
    Code_236("236", "Commercial sales of non-customised software provided for downloading or electronically made available with single payment"),
    Code_240_01("240/01", "Fees for processing - processing done on materials (excluding gold, platinum, crude oil, refined petroleum products, diamonds, steel, coal and iron ore)"),
    Code_240_02("240/02", "Fees for processing - processing done on gold"),
    Code_240_03("240/03", "Fees for processing - processing done on platinum"),
    Code_240_04("240/04", "Fees for processing - processing done on crude oil"),
    Code_240_05("240/05", "Fees for processing - processing done on refined petroleum products"),
    Code_240_06("240/06", "Fees for processing - processing done on diamonds"),
    Code_240_07("240/07", "Fees for processing - processing done on steel"),
    Code_240_08("240/08", "Fees for processing - processing done on coal"),
    Code_240_09("240/09", "Fees for processing - processing done on iron ore"),
    Code_241("241", "Repairs and maintenance on machinery and equipment"),
    Code_242("242", "Architectural, engineering and other technical services"),
    Code_243("243", "Agricultural, mining, waste treatment and depollution services"),
    Code_250("250", "Travel services for non-residents - business travel"),
    Code_251("251", "Travel services for non-residents - holiday travel"),
    Code_252("252", "Foreign exchange accepted by residents from non-residents"),
    Code_255("255", "Travel services for residents - business travel"),
    Code_256("256", "Travel services for residents - holiday travel"),
    Code_260("260", "Proceeds for travel services in respect of third parties - business travel"),
    Code_261("261", "Proceeds for travel services in respect of third parties - holiday travel"),
    Code_265("265", "Proceeds for telecommunication services"),
    Code_266("266", "Proceeds for information services including data, news related and news agency fees"),
    Code_270_01("270/01", "Proceeds for passenger services - road"),
    Code_270_02("270/02", "Proceeds for passenger services - rail"),
    Code_270_03("270/03", "Proceeds for passenger services - sea"),
    Code_270_04("270/04", "Proceeds for passenger services - air"),
    Code_271_01("271/01", "Proceeds for freight services - road"),
    Code_271_02("271/02", "Proceeds for freight services - rail"),
    Code_271_03("271/03", "Proceeds for freight services - sea"),
    Code_271_04("271/04", "Proceeds for freight services - air"),
    Code_272_01("272/01", "Proceeds for other transport services - road"),
    Code_272_02("272/02", "Proceeds for other transport services - rail"),
    Code_272_03("272/03", "Proceeds for other transport services - sea"),
    Code_272_04("272/04", "Proceeds for other transport services - air"),
    Code_273_01("273/01", "Proceeds for postal and courier services - road"),
    Code_273_02("273/02", "Proceeds for postal and courier services - rail"),
    Code_273_03("273/03", "Proceeds for postal and courier services - sea"),
    Code_273_04("273/04", "Proceeds for postal and courier services - air"),
    Code_275("275", "Commission and fees"),
    Code_276("276", "Proceeds for financial services charged for advice provided"),
    Code_280("280", "Proceeds for construction services"),
    Code_281("281", "Proceeds for government services"),
    Code_282("282", "Diplomatic transfers"),
    Code_285("240/01", "Export advance payment"),
    Code_287("287", "Proceeds for legal services"),
    Code_288("288", "Proceeds for accounting services"),
    Code_289("289", "Proceeds for management consulting services"),
    Code_290("290", "Proceeds for public relation services"),
    Code_291("291", "Proceeds for advertising & market research services"),
    Code_292("292", "Proceeds for managerial services"),
    Code_293("293", "Proceeds for medical and dental services"),
    Code_294("294", "Proceeds for educational services"),
    Code_295("295", "Operational leasing"),
    Code_296("296", "Proceeds for cultural and recreational services"),
    Code_297("297", "Proceeds for other business services not included elsewhere"),
    Code_300("300", "Adjustments / Reversals / Refunds related to income and yields on financial assets"),
    Code_301("301", "Dividends"),
    Code_302("302", "Branch profits"),
    Code_303("303", "Compensation paid by a non-resident to a resident employee temporarily abroad (excluding remittances)"),
    Code_304("304", "Compensation paid by a non-resident to a non-resident employee in South Africa (excluding remittances)"),
    Code_305("305", "Compensation paid by a non-resident to a migrant worker employee (excluding remittances)"),
    Code_306("306", "Compensation paid by a non-resident to a foreign national contract worker employee (excluding remittances)"),
    Code_307("307", "Commission or brokerage"),
    Code_308("308", "Rental"),
    Code_309_01("309/01", "Interest received from a resident temporarily abroad in respect of loans"),
    Code_309_02("309/02", "Interest received from a non-resident in respect of individual loans"),
    Code_309_03("309/03", "Interest received from a non-resident in respect of study loans"),
    Code_309_04("309/04", "Interest received from a non-resident in respect of shareholders loans"),
    Code_309_05("309/05", "Interest received from a non-resident in respect of third party loans"),
    Code_309_06("309/06", "Interest received from a non-resident in respect of trade finance loans"),
    Code_309_07("309/07", "Interest received from a non-resident in respect of a bond"),
    Code_309_08("309/08", "Interest received not in respect of loans"),
    Code_310_01("310/01", "Income in respect of inward listed securities equity individual"),
    Code_310_02("310/02", "Income in respect of inward listed securities equity corporate"),
    Code_310_03("310/03", "Income in respect of inward listed securities equity bank"),
    Code_310_04("310/04", "Income in respect of inward listed securities equity institution"),
    Code_311_01("311/01", "Income in respect of inward listed securities debt individual"),
    Code_311_02("311/02", "Income in respect of inward listed securities debt corporate"),
    Code_311_03("311/03", "Income in respect of inward listed securities debt bank"),
    Code_311_04("311/04", "Income in respect of inward listed securities debt institution"),
    Code_312_01("312/01", "Income in respect of inward listed securities derivatives individual"),
    Code_312_02("312/02", "Income in respect of inward listed securities derivatives corporate"),
    Code_312_03("312/03", "Income in respect of inward listed securities derivatives bank"),
    Code_312_04("312/04", "Income in respect of inward listed securities derivatives institution"),
    Code_313("313", "Income earned abroad by a resident on an individual investment"),
    Code_400("400", "Adjustments / Reversals / Refunds related to transfers of a current nature"),
    Code_401("401", "Gifts"),
    Code_402("402", "Annual contributions"),
    Code_403("403", "Contributions in respect of social security schemes"),
    Code_404("404", "Contributions in respect of charitable, religious and cultural (excluding research and development)"),
    Code_405("405", "Other donations / aid to Government (excluding research and development)"),
    Code_406("406", "Other donations / aid to private sector (excluding research and development)"),
    Code_407("407", "Pensions"),
    Code_408("408", "Annuities (pension related)"),
    Code_409("409", "Inheritances"),
    Code_410("410", "Alimony"),
    Code_411_01("411/01", "Tax - Income tax"),
    Code_411_02("411/02", "Tax - VAT refunds"),
    Code_411_03("411/03", "Tax - Other"),
    Code_412("412", "Insurance premiums (non life/short term)"),
    Code_413("413", "Insurance claims (non life/short term)"),
    Code_414("414", "Insurance premiums (life)"),
    Code_415("415", "Insurance claims (life)"),
    Code_416("416", "Migrant worker remittances (excluding compensation)"),
    Code_417("417", "Foreign national contract worker remittances (excluding compensation)"),
    Code_500("500", "Adjustments / Reversals / Refunds related to capital transfers and immigrants"),
    Code_501("501", "Donations to SA Government for fixed assets"),
    Code_502("502", "Donations to corporate entities - fixed assets"),
    Code_503("503", "Investment into property by a non-resident corporate entity"),
    Code_504("504", "Disinvestment of property by a resident corporate entity"),
    Code_510_01("510/01", "Investment into property by a non-resident individual"),
    Code_510_02("510/02", "Investment by a non-resident individual - other"),
    Code_511_01("511/01", "Disinvestment of capital by a resident individual - Shares"),
    Code_511_02("511/02", "Disinvestment of capital by a resident individual - Bonds"),
    Code_511_03("511/03", "Disinvestment of capital by a resident individual - Money market instruments"),
    Code_511_04("511/04", "Disinvestment of capital by a resident individual - Deposits with a foreign bank"),
    Code_511_05("511/05", "Disinvestment of capital by a resident individual - Mutual funds / collective investment schemes"),
    Code_511_06("511/06", "Disinvestment of capital by a resident individual - Property"),
    Code_511_07("511/07", "Disinvestment of capital by a resident individual - Other"),
    Code_516("516", "Repatriation of capital, on instruction by the FSD, of a foreign investment by a resident individual in respect of cross-border flows"),
    Code_517("517", "Repatriation of capital, on instruction by the FSD, of a foreign investment by a resident individual originating from an account conducted in foreign currency held at an AD in SA"),
    Code_530_01("530/01", "Immigration"),
    Code_600("600", "Adjustments / Reversals / Refunds related to financial investments/disinvestments and prudential investments"),
    Code_601_01("601/01", "Investment in listed shares by a non-resident"),
    Code_601_02("601/02", "Investment in non-listed shares by a non-resident"),
    Code_602_01("602/01", "Investment into money market instruments by a non-resident"),
    Code_603_01("603/01", "Investment into listed bonds by a non-resident (excluding loans)"),
    Code_603_02("603/02", "Investment into non-listed bonds by a non-resident (excluding loans)"),
    Code_605_01("605/01", "Disinvestment of shares by resident - Agriculture, hunting, forestry and fishing"),
    Code_605_02("605/02", "Disinvestment of shares by resident - Mining, quarrying and exploration"),
    Code_605_03("605/03", "Disinvestment of shares by resident - Manufacturing"),
    Code_605_04("605/04", "Disinvestment of shares by resident - Electricity, gas and water supply"),
    Code_605_05("605/05", "Disinvestment of shares by resident - Construction"),
    Code_605_06("605/06", "Disinvestment of shares by resident - Wholesale, retail, repairs, hotel and restaurants"),
    Code_605_07("605/07", "Disinvestment of shares by resident - Transport and communication"),
    Code_605_08("605/08", "Disinvestment of shares by resident - Financial services"),
    Code_605_09("605/09", "Disinvestment of shares by resident - Community, social and personal services"),
    Code_610_01("610/01", "Inward listed securities equity individual buy back"),
    Code_610_02("610/02", "Inward listed securities equity corporate buy back"),
    Code_610_03("610/03", "Inward listed securities equity bank buy back"),
    Code_610_04("610/04", "Inward listed securities equity institution buy back"),
    Code_611_01("611/01", "Inward listed securities debt individual redemption"),
    Code_611_02("611/02", "Inward listed securities debt corporate redemption"),
    Code_611_03("611/03", "Inward listed securities debt bank redemption"),
    Code_611_04("611/04", "Inward listed securities debt institution redemption"),
    Code_612_01("612/01", "Inward listed securities derivatives individual proceeds"),
    Code_612_02("612/02", "Inward listed securities derivatives corporate proceeds"),
    Code_612_03("612/03", "Inward listed securities derivatives bank proceeds"),
    Code_612_04("612/04", "Inward listed securities derivatives institution proceeds"),
    Code_615_01("615/01", "Disinvestment by resident institutional investor - Asset Manager"),
    Code_615_02("615/02", "Disinvestment by resident institutional investor - Collective Investment Scheme"),
    Code_615_03("615/03", "Disinvestment by resident institutional investor - Retirement Fund"),
    Code_615_04("615/04", "Disinvestment by resident institutional investor - Life Linked"),
    Code_615_05("615/05", "Disinvestment by resident institutional investor - Life Non Linked"),
    Code_616("616", "Bank prudential disinvestment"),
    Code_700("700", "Adjustments / Reversals / Refunds related to derivatives"),
    Code_701_01("701/01", "Options - listed"),
    Code_701_02("701/02", "Options - unlisted"),
    Code_702_01("702/01", "Futures - listed"),
    Code_702_02("702/02", "Futures - unlisted"),
    Code_703_01("703/01", "Warrants - listed"),
    Code_703_02("703/02", "Warrants - unlisted"),
    Code_704_01("704/01", "Gold hedging - listed"),
    Code_704_02("704/02", "Gold hedging - unlisted"),
    Code_705_01("705/01", "Derivative not specified above - listed"),
    Code_705_02("705/02", "Derivative not specified above - unlisted"),
    Code_800("800", "Adjustments / Reversals / Refunds related to loan and miscellaneous payments"),
    Code_801("801", "Trade finance loan drawn down in South Africa"),
    Code_802("802", "International Bond drawn down"),
    Code_803("803", "Loan made to a resident by a non-resident shareholder"),
    Code_804("804", "Loan made to a resident by a non-resident third party"),
    Code_810("810", "Repayment by a resident temporarily abroad of a loan granted by a resident"),
    Code_815("815", "Repayment of an individual loan to a resident"),
    Code_816("816", "Repayment of a study loan to a resident"),
    Code_817("817", "Repayment of a shareholders loan to a resident"),
    Code_818("818", "Repayment of a third party loan to a resident (excluding shareholders)"),
    Code_819("819", "Repayment of a trade finance loan to a resident"),
    Code_830("830", "Details of payments not classified"),
    Code_832("832", "Rand drafts/cheques drawn on vostro accounts (Only applicable if no description is available)"),
    Code_833("833", "Credit/Debit card company settlement as well as money remitter settlements");


    private final String categoryCode;
    private final String description;

    BOPcategoryMetaDataEnum(String categoryCode, String description){
        this.categoryCode = categoryCode;
        this.description = description;
    }

    public String getCategoryCode() {
        return categoryCode;
    }

    public String getDescription() {
        return description;
    }

    public String getDescriptionbycode(String categoryCode) {
        if (categoryCode.equalsIgnoreCase(categoryCode)) {
            return this.description;
        }else {
            return "";
        }
    }
}
